# ---
# apiVersion: v1
# data:
#  # Please follow instruction in document to generate new SSL certs
#  khulnasoft_ke.key: ""
#  khulnasoft_ke.crt: ""
# kind: Secret
# metadata:
#   annotations:
#     description: Kube Enforcer SSL certificates to communicate with Kube API server
#   labels:
#     deployedby: khulnasoft-yaml
#   name: kube-enforcer-ssl
#   namespace: khulnasoft
# type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    description: Khulnasoft Enforcer token secret
  labels:
    deployedby: khulnasoft-yaml
  name: khulnasoft-kube-enforcer-token
  namespace: khulnasoft
type: Opaque
data:
  ## In the Enforcers screen, edit the KubeEnforcer to get the token from the default KubeEnforcer group configuration. - Base64 encoded ##
  token: ""
