apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: khulnasoft-tm-db-pvc
  namespace: khulnasoft
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
status: {}
