# Create a PVC for the Khulnasoft Database
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: khulnasoft-db-pvc
  namespace: khulnasoft
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
# Create a PVC for the Khulnasoft Database
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: khulnasoft-audit-db-pvc
  namespace: khulnasoft
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi