apiVersion: v1
kind: Service
metadata:
  name: khulnasoft-gateway
  namespace: khulnasoft
  labels:
    app: khulnasoft-gateway
spec:
  type: LoadBalancer
  ports:
    - port: 8443
      protocol: TCP
      targetPort: 8443
      name: khulnasoft-gateway-ssl
    - port: 3622
      protocol: TCP
      targetPort: 3622
      name: khulnasoft-gateway
  selector:
    app: khulnasoft-gateway
---
apiVersion: v1
kind: Service
metadata:
  name: khulnasoft-web
  namespace: khulnasoft
  labels:
    app: khulnasoft-web
spec:      
  ports:
    - port: 443
      protocol: TCP
      targetPort: 8443
      name: khulnasoft-web-ssl
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: khulnasoft-web
  selector:
    app: khulnasoft-web
  type: LoadBalancer
