apiVersion: apps/v1
kind: Deployment
metadata:
  name: khulnasoft-web
  namespace: khulnasoft
  labels:
    app: khulnasoft-web
    khulnasoft.component: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: khulnasoft-web
  template:
    metadata:
      labels:
        app: khulnasoft-web
        khulnasoft.component: server
      name: khulnasoft-web
    spec:
      securityContext:
        runAsUser: 11431
        runAsGroup: 11433
        fsGroup: 11433
      serviceAccount: khulnasoft-sa
      restartPolicy: Always
      containers:
      - name: khulnasoft-web
        image: registry.khulnasoft.com/console:2022.4
        imagePullPolicy: IfNotPresent
#        resources:
#          limits:
#            cpu: 3000m
#            memory: 2Gi
#          requests:
#            cpu: 2000m
#            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        envFrom:
        - configMapRef:
            name: khulnasoft-csp-server-config
      ##  - secretRef:
      #      name: khulnasoft-csp-server-secret
        env:
        - name: KHULNASOFT_PUBSUB_DBPASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: khulnasoft-db
        - name: SCALOCK_AUDIT_DBPASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: khulnasoft-audit-db
        - name: SCALOCK_DBPASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: khulnasoft-db
      #   volumeMounts:
      #   - mountPath: /opt/khulnasoft/ssl
      #     name: khulnasoft-grpc-web
      #     readOnly: true
      # volumes:
      # - name: khulnasoft-grpc-web
      #   secret:
      #     secretName: khulnasoft-grpc-web
      #     items:
      #     - key: khulnasoft_web.crt
      #       path: cert.pem
      #     - key: khulnasoft_web.key
      #       path: key.pem
      #     - key: rootCA.crt
      #       path: ca.pem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: khulnasoft-gateway
    khulnasoft.component: gateway
  name: khulnasoft-gateway
  namespace: khulnasoft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: khulnasoft-gateway
  template:
    metadata:
      labels:
        app: khulnasoft-gateway
        khulnasoft.component: gateway
      name: khulnasoft-gateway
    spec:
      securityContext:
        runAsUser: 11431
        runAsGroup: 11433
        fsGroup: 11433
      serviceAccount: khulnasoft-sa
      restartPolicy: Always
      containers:
      - name: khulnasoft-gateway
        image: registry.khulnasoft.com/gateway:2022.4
        imagePullPolicy: IfNotPresent
#        resources:
#          limits:
#            cpu: 1500m
#            memory: 4Gi
#          requests:
#            cpu: 1000m
#            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /
            port: 8082
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          tcpSocket:
            port: 8443
          initialDelaySeconds: 60
          periodSeconds: 30
        ports:
        - containerPort: 3622
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        envFrom:
        - configMapRef:
            name: khulnasoft-csp-server-config
        env:
        - name: SCALOCK_DBPASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: khulnasoft-db
        - name: SCALOCK_AUDIT_DBPASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: khulnasoft-audit-db
      #   volumeMounts:
      #   - mountPath: /opt/khulnasoft/ssl
      #     name: khulnasoft-grpc-gateway
      #     readOnly: true
      # volumes:
      # - name: khulnasoft-grpc-gateway
      #   secret:
      #     secretName: khulnasoft-grpc-gateway
      #     items:
      #     - key: khulnasoft_gateway.crt
      #       path: cert.pem
      #     - key: khulnasoft_gateway.key
      #       path: key.pem
      #     - key: rootCA.crt
      #       path: ca.pem
