apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: khulnasoft-psp-cr
rules:
- apiGroups: ["extensions"]
  resourceNames: ["ibm-privileged-psp"]
  resources: ["podsecuritypolicies"]
  verbs: ["use"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: khulnasoft-psp-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: khulnasoft-privileged-clusterrole
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:khulnasoft
---
apiVersion: v1
imagePullSecrets:
- name: khulnasoft-registry
kind: ServiceAccount
metadata:
  annotations:
    description: Service account for pulling Khulnasoft images and for Khulnasoft privileged
  labels:
    deployedby: khulnasoft-yaml
  name: khulnasoft-sa
  namespace: khulnasoft
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.example.com/aggregate-to-monitoring: "true"
    deployedby: khulnasoft-yaml
  name: khulnasoft-discovery-cr
  namespace: khulnasoft
rules:
- apiGroups: [""]
  resources: ["nodes", "services", "endpoints", "pods", "deployments", "namespaces","componentstatuses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: khulnasoft-discovery-crb
  namespace: khulnasoft
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: khulnasoft-discovery-cr
subjects:
  - kind: ServiceAccount
    name: khulnasoft-sa
    namespace: khulnasoft