# apiVersion: v1
# data:
#   # Please follow instruction in document to generate new SSL certs
#   tls.key: ""
#   tls.crt: ""
# kind: Secret
# metadata:
#   annotations:
#     description: Khulnasoft LB SSL certificates to communicate with external enforcers using TLS
#   labels:
#     deployedby: khulnasoft-yaml
#   name: khulnasoft-lb-certs
#   namespace: khulnasoft
# type: Opaque