apiVersion: v1
imagePullSecrets:
- name: khulnasoft-registry
kind: ServiceAccount
metadata:
  annotations:
    description: Service account for pulling Khulnasoft images and for Khulnasoft privileged
  labels:
    deployedby: khulnasoft-yaml
  name: khulnasoft-sa
  namespace: khulnasoft
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: khulnasoft-discovery-cr
  labels:
    rbac.example.com/aggregate-to-monitoring: "true"
rules:
- apiGroups: [""]
  resources: ["nodes", "services", "endpoints", "pods", "deployments", "namespaces","componentstatuses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["imagestreams", "imagestreams/layers"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: khulnasoft-discovery-crb
roleRef:
  name: khulnasoft-discovery-cr
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
subjects:
  - kind: ServiceAccount
    name: khulnasoft-sa
    namespace: khulnasoft
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-reader
subjects:
  - kind: ServiceAccount
    name: khulnasoft-sa
    namespace: khulnasoft
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-reader
---
allowHostDirVolumePlugin: true
allowHostIPC: false
allowHostNetwork: false
allowHostPID: true
allowHostPorts: false
allowPrivilegeEscalation: false
allowPrivilegedContainer: false
allowedCapabilities:
- SYS_ADMIN
- NET_ADMIN
- NET_RAW
- SYS_PTRACE
- KILL
- MKNOD
- SETGID
- SETUID
- SYS_MODULE
- AUDIT_CONTROL
- SYSLOG
- SYS_CHROOT
apiVersion: security.openshift.io/v1
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
groups: []
kind: SecurityContextConstraints
metadata:
  annotations:
    kubernetes.io/description: khulnasoft scc provides all features of the restricted SCC
      but allows users to run with any non-root UID and access hostPath. The user must
      specify the UID or it must be specified on the by the manifest of the container runtime.
    release.openshift.io/create-only: "true"
  name: khulnasoft-scc
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities: null
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:khulnasoft:khulnasoft-sa
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret
- hostPath
