apiVersion: v1
data:
  ### Khulnasoft database password. Defaults to "password". Please change the same if needed.
  password: cGFzc3dvcmQK
kind: Secret
metadata:
  annotations:
    description: Khulnasoft database password secret
  labels:
    deployedby: khulnasoft-yaml
  name: khulnasoft-db
  namespace: khulnasoft
type: Opaque
---
apiVersion: v1
data:
  ### Khulnasoft database password. Defaults to "password". Please change the same if needed.
  password: cGFzc3dvcmQK
kind: Secret
metadata:
  annotations:
    description: Khulnasoft audit database password secret
  labels:
    deployedby: khulnasoft-yaml
  name: khulnasoft-audit-db
  namespace: khulnasoft
type: Opaque