apiVersion: v1
data:
  password: cGFzc3dvcmQK
kind: Secret
metadata:
  annotations:
    description: Khulnasoft Tenant Manager database password secret
  creationTimestamp: null
  labels:
    deployedby: khulnasoft-yaml
  name: khulnasoft-tm-db
  namespace: khulnasoft
type: Opaque
