apiVersion: v1
kind: Service
metadata:
  name: khulnasoft-tenantmanager
  namespace: khulnasoft
  labels:
    app: khulnasoft-tenantmanager
spec:
  ports:
    - port: 8081
      name: khulnasoft-tenantmanager
      protocol: TCP
      targetPort: 8081
    - port: 443
      name: khulnasoft-tenantmanager-ssl
      protocol: TCP
      targetPort: 8444
  selector:
    app: khulnasoft-tenantmanager
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: khulnasoft-tenantmanager
  namespace: khulnasoft
spec:
  selector:
    matchLabels:
      app: khulnasoft-tenantmanager
  template:
    metadata:
      labels:
        app: khulnasoft-tenantmanager
      name: khulnasoft-tenantmanager
    spec:
      serviceAccount: khulnasoft-sa
      securityContext:
        runAsUser: 11431
        runAsGroup: 11433
        fsGroup: 11433
      containers:
      - name: khulnasoft-tenantmanager
        image: registry.khulnasoft.com/tenantmanager:2022.4
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 30
        env:
        - name: KHULNASOFT_TM_DBPASSWORD
          valueFrom:
            secretKeyRef:
              name: khulnasoft-tm-db
              key: password
        - name: KHULNASOFT_TM_AUDIT_DBPASSWORD
          valueFrom:
            secretKeyRef:
              name: khulnasoft-tm-db
              key: password
        envFrom:
        - configMapRef:
            name: khulnasoft-tenant-manager-config
        ports:
          - containerPort: 8081
            protocol: TCP
          - containerPort: 8444
            protocol: TCP
