apiVersion: v1
kind: Secret
metadata:
  annotations:
    description: Khulnasoft Scanner username and password
  labels:
    deployedby: khulnasoft-yaml
  name: khulnasoft-scanner
  namespace: khulnasoft
type: Opaque
data:
  # Khulnasoft Scanner Username - Base64 Encoded
  KHULNASOFT_SCANNER_USERNAME: ""
  # Khulnasoft Scanner Password - Base64 Encoded
  KHULNASOFT_SCANNER_PASSWORD: ""
  # Base64 Encoded - Khulnasoft web root cert
  khulnasoft-web-root-cert: ""
# ---
# Use the following kubectl command to create registry secret to authenticate during image pull
## kubectl create secret docker-registry khulnasoft-registry --docker-server=<your-registry-server> --docker-username=<your-name> --docker-password=<your-pword> --docker-email=<your-email> -n khulnasoft
# If you already have the credentials already configured in .docker/config.json file use the following secret block to add docker pull secrets
# apiVersion: v1
# data:
#   .dockerconfigjson: ## Input Needed ##
# kind: Secret
# metadata:
#   annotations:
#     description: Secret for pulling Khulnasoft images
#   labels:
#     deployedby: khulnasoft-yaml
#   name: khulnasoft-registry
#   namespace: khulnasoft
# type: kubernetes.io/dockerconfigjson