apiVersion: v1
data:
  ### Khulnasoft database password. Defaults to "password". Please change the same if needed.
  password: cGFzc3dvcmQK
kind: Secret
metadata:
  annotations:
    description: Khulnasoft database password secret
  labels:
    deployedby: khulnasoft-yaml
  name: khulnasoft-db
  namespace: khulnasoft
type: Opaque
---
apiVersion: v1
data:
  ### Khulnasoft database password. Defaults to "password". Please change the same if needed.
  password: cGFzc3dvcmQK
kind: Secret
metadata:
  annotations:
    description: Khulnasoft audit database password secret
  labels:
    deployedby: khulnasoft-yaml
  name: khulnasoft-audit-db
  namespace: khulnasoft
type: Opaque
# ---
# The following certs is used to provide secure HTTPS communication between all the Khulnasoft components
# If the certs are self signed the same needs to be mounted into scanner container for secure HTTPS communication.
# apiVersion: v1
# data:
#  khulnasoft_web.key:  ## Input Needed  -  base64 value of Private cert ##
#  khulnasoft_web.crt:  ## Input Needed  -  base64 value of Public cert ##
#  rootCA.crt:  ## Input Needed  -  base64 value of Root CA cert ##
# kind: Secret
# metadata:
#   annotations:
#     description: Khulnasoft SSL certificates
#   labels:
#     deployedby: khulnasoft-yaml
#   name: khulnasoft-grpc-web
#   namespace: khulnasoft
# type: Opaque
# ---
# apiVersion: v1
# data:
#  khulnasoft_gateway.key: ## Input Needed  -  base64 value of Private cert ##
#  khulnasoft_gateway.crt: ## Input Needed  -  base64 value of Public cert ##
#  rootCA.crt: ## Input Needed  -  base64 value of Root CA cert ##
# kind: Secret
# metadata:
#   annotations:
#     description: Khulnasoft SSL certificates
#   labels:
#     deployedby: khulnasoft-yaml
#   name: khulnasoft-grpc-gateway
#   namespace: khulnasoft
# type: Opaque
# ---
# Use the following kubectl command to create registry secret to authenticate during image pull
## kubectl create secret docker-registry khulnasoft-registry --docker-server=<your-registry-server> --docker-username=<your-name> --docker-password=<your-pword> --docker-email=<your-email> -n khulnasoft
# If you already have the credentials already configured in .docker/config.json file use the following secret block to add docker pull secrets
# apiVersion: v1
# data:
#   .dockerconfigjson: ## Input Needed ##
# kind: Secret
# metadata:
#   annotations:
#     description: Secret for pulling Khulnasoft images
#   labels:
#     deployedby: khulnasoft-yaml
#   name: khulnasoft-registry
#   namespace: khulnasoft
# type: kubernetes.io/dockerconfigjson
# ---
# # Use the following secret block to add admin password and license as env variable. If not set the admin will be prompted for the same up on initial login.
# apiVersion: v1
# data:
#   ### Khulnasoft admin password
#   ADMIN_PASSWORD: ## Input Needed ##
#   LICENSE_TOKEN: ## Input Needed ##
# kind: Secret
# metadata:
#   annotations:
#     description: Khulnasoft administrator password and License tokens
#   labels:
#     deployedby: khulnasoft-yaml
#   name: khulnasoft-csp-server-secret
#   namespace: khulnasoft
# type: Opaque
